version: '2.4'
services:
  postgres:
    image: postgres:15.1
    # profiles:
    #   - "db"
    container_name: bot-postgres
    volumes:
      - buybot:/var/lib/postgresql/data

    ports:
    - 6432:5432

    logging:
      driver: json-file
      options:
        max-size: '100m'
        max-file: '5'

    environment:
     - POSTGRES_USER=${DBUSER}
     - POSTGRES_PASSWORD=${DBPASSWORD}     
     - POSTGRES_DB=${DBNAME}
     - DATABASE_HOST=${DBHOST}
     - DATABASE_PORT=${DBPORT}

    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5

  buybot:
    build: 
      context: .

    image: buybot:latest
    # profiles:
    #   - "app"
    container_name: buybot
    environment:
      - TOKEN=${TOKEN}
      - DBNAME = ${DBNAME}
      - DBUSER = ${DBUSER}
      - DBPASSWORD = ${DBPASSWORD}
      - DBHOST  = ${DBHOST}
      - DBPORT = ${DBPORT}
    hostname: buybot
    # ports:
    #   - 8081:8081
    
    logging:
      driver: json-file
      options:
        max-size: '100m'
        max-file: '5'
      
  # migrate:
  #     image: migrate/migrate
  #     # networks:
  #     #   - new
  #     volumes:
  #        - .:/migrations
  #     command: ["-path", "/migrations", "-database",  "postgres://postgres:pass@postgres:5432/test?sslmode=disable", "down", "1"]
  #     links: 
  #       - postgres
  #     depends_on:
  #     - postgres
volumes:
  buybot: